const DEFAULT_PORT = 4963
const DEFAULT_ADDRESS = '0.0.0.0'
const DEFAULT_DIRECTORY = './'

const DEFAULT_THUMB_THRESHOLD = 1024 * 1024
const DEFAULT_THUMB_SIZE = 400
const DEFAULT_THUMB_LIMIT = 3

module.exports = {
    DEFAULT_PORT,
    DEFAULT_ADDRESS,
    DEFAULT_DIRECTORY,

    DEFAULT_THUMB_THRESHOLD,
    DEFAULT_THUMB_SIZE,
    DEFAULT_THUMB_LIMIT
}